import { useState } from "react";
import { jsPDF } from "jspdf";

export default function Report() {
  const [form, setForm] = useState({
    has_gst: false,
    has_udyam: false,
    has_license: false,
    has_pan: false,
    has_pollution: false,
    has_trade: false,
  });

  const handleChange = (key) => {
    setForm({ ...form, [key]: !form[key] });
  };

  const getScore = () => {
    const filled = Object.values(form).filter(Boolean).length;
    return Math.round((filled / 6) * 100);
  };

  const getAdvice = (key) => {
    switch (key) {
      case "has_gst":
        return "Apply for GST at https://www.gst.gov.in for tax compliance.";
      case "has_udyam":
        return "Register on https://udyamregistration.gov.in to access MSME schemes.";
      case "has_license":
        return "Apply via MCD or DSIIDC for your Business License.";
      case "has_pan":
        return "Get a PAN card for official tax and banking use.";
      case "has_pollution":
        return "Apply for Pollution NOC at https://dpcc.delhigovt.nic.in.";
      case "has_trade":
        return "Use https://mcdonline.nic.in to get your Trade License.";
      default:
        return "";
    }
  };

  const generatePDF = () => {
    const doc = new jsPDF();
    const score = getScore();
    const date = new Date().toLocaleString();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("GovMSE+ Compliance Report", 20, 20);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(`Generated: ${date}`, 20, 30);
    doc.text(`GovScore: ${score} / 100`, 20, 40);

    doc.setFont("helvetica", "bold");
    doc.text("Status & Recommendations", 20, 55);

    const map = {
      has_gst: "GST Certificate",
      has_udyam: "Udyam Registration",
      has_license: "Business License",
      has_pan: "PAN Card",
      has_pollution: "Pollution NOC",
      has_trade: "Trade License",
    };

    let y = 65;
    doc.setFont("helvetica", "normal");
    for (let key in form) {
      const label = map[key];
      const available = form[key];
      doc.text(`${label}: ${available ? "✅ Available" : "❌ Missing"}`, 25, y);
      if (!available) {
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`→ ${getAdvice(key)}`, 28, y + 6, { maxWidth: 160 });
        y += 14;
        doc.setFontSize(12);
        doc.setTextColor(0);
      } else {
        y += 10;
      }
    }

    y += 10;
    doc.setFont("helvetica", "bold");
    doc.text("Useful Resources", 20, y);
    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.textWithLink("• Udyam Portal", 25, y, { url: "https://udyamregistration.gov.in" });
    y += 6;
    doc.textWithLink("• Delhi eDistrict", 25, y, { url: "https://edistrict.delhigovt.nic.in" });
    y += 6;
    doc.textWithLink("• GST Portal", 25, y, { url: "https://www.gst.gov.in" });
    y += 6;
    doc.textWithLink("• Trade License - MCD", 25, y, { url: "https://mcdonline.nic.in" });

    y += 12;
    doc.setFontSize(11);
    doc.setTextColor(80);
    doc.text("This report was auto-generated by GovMSE+ to support MSME compliance.", 20, y);

    doc.save("GovMSE_Compliance_Report.pdf");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#4169E1] via-[#b3e5c9] to-[#e8fff3] p-6 flex flex-col justify-between">
      <div className="max-w-3xl w-full mx-auto bg-white shadow-xl rounded-2xl p-8">
        <h1 className="text-3xl font-extrabold text-[#2a2f45] mb-6">Generate Your Compliance Report</h1>

        <p className="text-gray-800 mb-4 text-lg">
          Tick the documents your MSME currently holds. Your GovScore will be calculated and used to generate a downloadable PDF.
        </p>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6 text-md">
          {[
            ["has_gst", "GST Certificate"],
            ["has_udyam", "Udyam Registration"],
            ["has_license", "Business License (MCD/DSIIDC)"],
            ["has_pan", "PAN Card"],
            ["has_pollution", "Pollution NOC"],
            ["has_trade", "Trade License"],
          ].map(([key, label]) => (
            <label key={key} className="flex items-center gap-2 bg-gray-100 px-4 py-3 rounded shadow">
              <input
                type="checkbox"
                checked={form[key]}
                onChange={() => handleChange(key)}
                className="accent-blue-600 w-5 h-5"
              />
              <span>{label}</span>
            </label>
          ))}
        </div>

        <div className="text-center mb-6">
          <p className="text-lg font-semibold text-[#43CD80]">Your GovScore: {getScore()} / 100</p>
        </div>

        <div className="text-center">
          <button
            onClick={generatePDF}
            className="bg-green-600 text-white px-6 py-3 rounded-lg hover:bg-green-700 transition"
          >
            Generate PDF Report
          </button>
        </div>
      </div>

      {/* Footer */}
      <footer className="mt-10 bg-gradient-to-r from-[#4169E1] to-[#43CD80] text-white text-sm py-6">
        <div className="max-w-7xl mx-auto px-4 flex flex-col md:flex-row justify-between items-center gap-4">
          <div>&copy; {new Date().getFullYear()} GovMSE. All rights reserved.</div>
          <div>
            Contact us:{" "}
            <a href="mailto:support@govmse.in" className="underline">
              support@govmse.in
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
